language: node_js
sudo: false
node_js:
  - "lts/*"
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
  - npm run test:coverage
  - npm run coveralls
